char troll(char a)
{
  if (a=='a')
 {
  do
  {
   cout<<"SPONSORED BY AMOLAPATTY.COM";
  }
  while(1==1);
 }
 else if (a=='b')
{
  do
  {
   cout<<"BHRAMARAHA SANGLAPANTI\n";
  }
  while (1==1);
}

 else if (a=='c')
 {
   do
  {
   cout<<"CIBOLA THE C SHAPED PARABOLA\n";
  }
  while (1==1);
 }

 else if (a=='d')
 {
   do
  {
   cout<<"DAM MARO DAM.................\n";
  }
  while (1==1);
 }

 else if (a=='e')
 {
   do
  {
   cout<<"E JAMINWA HAMRO NAAM LIKHI HAI TUM BEWRA KA KAR RAHA HAI E JAMEEN PAR??\n\n";
  }
  while (1==1);
 }

 else if (a=='f')
 {
   do
  {
   cout<<"";
  }
  while (1==1);
 }

 else if (a=='g')
 {
   do
  {
   cout<<"";
  }
  while (1==1);
 }

 else if (a=='h')
 {
   do
  {
   cout<<"HEBI !!! HEBI !!! HEBI !!! HEBI!!! HEBI!!! HEBI!!!\n";
  }
  while (1==1);
 }

 else if (a=='i')
 {
   do
  {
   cout<<"I AM A DISCO DANCER.........(CHESSY MUSIC)\n";
  }
  while (1==1);
 }

 else if (a=='j')
 {
   do
  {
   cout<<"";
  }
  while (1==1);
 }

 else if (a=='k')
 {
   do
  {
   cout<<"";
  }
  while (1==1);
 }
 else if (a=='l')
  {
   do
  {
   cout<<"";
  }
  while (1==1);
  }

 else if (a=='m')
  {
   do
  {
   cout<<"";
  }
  while (1==1);
  }

 else if (a=='n')
   {
   do
  {
   cout<<"";
  }
  while (1==1);
   }

 else if (a=='o')
    {
    do
  {
   cout<<"";
  }
  while (1==1);
    }

 else if (a=='p')
     {
    do
  {
   cout<<"";
  }
  while (1==1);
     }

 else if (a=='q')
 {
   do
  {
   cout<<"";
  }
  while (1==1);
 }

 else if (a=='r')
 {
   do
  {
   cout<<"";
  }
  while (1==1);
  }

 else if (a=='s')
 {
   do
  {
   cout<<"";
  }
  while (1==1);
 }

 else if (a=='t')
 {
   do
  {
   cout<<"TROLOLOLOLOLOLOLOLOLOLOLOLOLOLOLOLOLOLOLOLOLOLOLOLOLOL\n";
  }
  while (1==1);
 }

 else if (a=='u')
  {
   do
  {
   cout<<"";
  }
  while (1==1);
  }
 else if (a=='v')
  {
   do
  {
   cout<<"";
  }
  while (1==1);
   }
 else if (a=='w')
  {
   do
  {
   cout<<"";
  }
  while (1==1);
  }
 else if (a=='x')
  {
   do
  {
   cout<<"";
  }
  while (1==1);
  }
 else if (a=='y')
  {
   do
  {
   cout<<"";
  }
  while (1==1);
   }
 else if (a=='z')
  {
   do
  {
   cout<<"";
  }
  while (1==1);
}
return 0;
}